apiVersion: v1
kind: Service
metadata:
  name: order-service-api
spec:
  type: NodePort
  selector:
    app: order-service-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30100 # mirrors the 8100 host port used in docker-compose
