apiVersion: v1
kind: Service
metadata:
  name: payment-service-api
spec:
  type: NodePort
  selector:
    app: payment-service-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30300 # mirrors the 8300 host port used in docker-compose
