# Generated by Django 5.2.17 on 2026-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_processedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='failed_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
