# Generated by Django 5.2.17 on 2026-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('topic', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('payload', models.JSONField()),
            ],
        ),
    ]
